// rambuffer10.v

// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module rambuffer10 (
		input  wire [559:0] data,      //      data.datain
		output wire [559:0] q,         //         q.dataout
		input  wire [9:0]   wraddress, // wraddress.wraddress
		input  wire [9:0]   rdaddress, // rdaddress.rdaddress
		input  wire         wren,      //      wren.wren
		input  wire         wrclock,   //   wrclock.clk
		input  wire         rdclock    //   rdclock.clk
	);

	rambuffer10_ram_2port_2021_24ycm2i ram_2port_0 (
		.data      (data),      //   input,  width = 560,      data.datain
		.q         (q),         //  output,  width = 560,         q.dataout
		.wraddress (wraddress), //   input,   width = 10, wraddress.wraddress
		.rdaddress (rdaddress), //   input,   width = 10, rdaddress.rdaddress
		.wren      (wren),      //   input,    width = 1,      wren.wren
		.wrclock   (wrclock),   //   input,    width = 1,   wrclock.clk
		.rdclock   (rdclock)    //   input,    width = 1,   rdclock.clk
	);

endmodule
