// clkctrl10.v

// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module clkctrl10 (
		input  wire  inclk,  //  inclk.clk
		input  wire  ena,    //    ena.export
		output wire  outclk  // outclk.clk
	);

	clkctrl10_altclkctrl_2000_flawdga altclkctrl_0 (
		.inclk  (inclk),  //   input,  width = 1,  inclk.clk
		.ena    (ena),    //   input,  width = 1,    ena.export
		.outclk (outclk)  //  output,  width = 1, outclk.clk
	);

endmodule
