// pll10_1.v

// Generated using ACDS version 22.4 94

`timescale 1 ps / 1 ps
module pll10_1 (
		input  wire       refclk,           //           refclk.clk
		output wire       locked,           //           locked.export
		input  wire       rst,              //            reset.reset
		input  wire       scanclk,          //          scanclk.clk
		input  wire       phase_en,         //         phase_en.phase_en
		input  wire       updn,             //             updn.updn
		input  wire [4:0] cntsel,           //           cntsel.cntsel
		output wire       phase_done,       //       phase_done.phase_done
		input  wire [2:0] num_phase_shifts, // num_phase_shifts.num_phase_shifts
		input  wire       refclk1,          //          refclk1.clk
		input  wire       extswitch,        //        extswitch.extswitch
		output wire       activeclk,        //        activeclk.activeclk
		output wire [1:0] clkbad,           //           clkbad.clkbad
		output wire       outclk_0,         //          outclk0.clk
		output wire       outclk_1,         //          outclk1.clk
		output wire       outclk_2,         //          outclk2.clk
		output wire       outclk_3          //          outclk3.clk
	);

	pll10_1_altera_iopll_1931_onadaoq iopll_0 (
		.refclk           (refclk),           //   input,  width = 1,           refclk.clk
		.locked           (locked),           //  output,  width = 1,           locked.export
		.rst              (rst),              //   input,  width = 1,            reset.reset
		.scanclk          (scanclk),          //   input,  width = 1,          scanclk.clk
		.phase_en         (phase_en),         //   input,  width = 1,         phase_en.phase_en
		.updn             (updn),             //   input,  width = 1,             updn.updn
		.cntsel           (cntsel),           //   input,  width = 5,           cntsel.cntsel
		.phase_done       (phase_done),       //  output,  width = 1,       phase_done.phase_done
		.num_phase_shifts (num_phase_shifts), //   input,  width = 3, num_phase_shifts.num_phase_shifts
		.refclk1          (refclk1),          //   input,  width = 1,          refclk1.clk
		.extswitch        (extswitch),        //   input,  width = 1,        extswitch.extswitch
		.activeclk        (activeclk),        //  output,  width = 1,        activeclk.activeclk
		.clkbad           (clkbad),           //  output,  width = 2,           clkbad.clkbad
		.outclk_0         (outclk_0),         //  output,  width = 1,          outclk0.clk
		.outclk_1         (outclk_1),         //  output,  width = 1,          outclk1.clk
		.outclk_2         (outclk_2),         //  output,  width = 1,          outclk2.clk
		.outclk_3         (outclk_3)          //  output,  width = 1,          outclk3.clk
	);

endmodule
